---
# - name: start apache
#   community.kubernetes.k8s:
#     definition:
#       kind: Deployment
#       apiVersion: apps/v1
#       metadata:
#         name: '{{ ansible_operator_meta.name }}-apache'
#         namespace: '{{ ansible_operator_meta.namespace }}'
#       spec:
#         replicas: "{{size}}"
#         selector:
#           matchLabels:
#             app: apache
#         template:
#           metadata:
#             labels:
#               app: apache
#           spec:
#             containers:
#             - name: apache
#               image: "httpd:alpine"
#               ports:
#                 - containerPort: 11211 # to be parametrized

- name: create service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        selector:
          app: apache
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80 # to be parametrized

- name: create configmap
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        example.property.1: hello
        example.property.2: world
        example.property.file: |-
          property.1=value-1
          property.2=value-2
          property.3=value-3
      


# - name: start apache
#   community.kubernetes.k8s:
#     definition:
#       kind: Deployment
#       apiVersion: apps/v1
#       metadata:
#         name: '{{ ansible_operator_meta.name }}-apache'
#         namespace: '{{ ansible_operator_meta.namespace }}'
#       spec:
#         replicas: "{{size}}"
#         selector:
#           matchLabels:
#             app: apache
#         template:
#           metadata:
#             labels:
#               app: apache
#           spec:
#             containers:
#             - name: apache
#               image: "httpd:alpine"
#               ports:
#                 - containerPort: 80            
