---
- name: start apache
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: '{{ size }}'
        selector:
          matchLabels:
            app: apache
        template:
          metadata:
            labels:
              app: apache
          spec:
            containers:
              - name: apache
                image: "rhscl/httpd-24-rhel7"
                ports:
                  - containerPort: 11211 # to be parametrized
                volumeMounts:
                  - name: html
                    mountPath: "/var/www/html/"
                    readOnly: true
                  - name: conf
                    mountPath: "/etc/httpd/conf/"  
                    readOnly: false # apache writes some stuff on /etc/httpd/conf

            volumes:
              - name: html
                configMap:
                  name: '{{ ansible_operator_meta.name }}-apache-html' # name of the html configmap
              - name: conf
                configMap:
                  name: '{{ ansible_operator_meta.name }}-apache-conf' # name of the conf configmap
                    
- name: create service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        selector:
          app: apache
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80 # to be parametrized

- name: create html configmap
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache-html'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        index.html: '{{ index_html }}' # key will define file name

- name: create httpd.conf configmap
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache-conf'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        httpd.conf: '{{ rendered_template }}'
  vars:
    rendered_template: "{{ lookup('template', './httpd.conf.j2') }}"


- name: create route
  community.kubernetes.k8s:
    definition:
      kind: Route
      apiVersion: route.openshift.io/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        host: '{{ route_name }}-apache-operator-system.apps-crc.testing'
        to:
          kind: Service
          name: sample-apache
          weight: 100
        port:
          targetPort: 80
        wildcardPolicy: None
