---
### workload
- name: start apache
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          app: apache
      spec:
        replicas: '{{ size }}'
        selector:
          matchLabels:
            app: apache
        template:
          metadata:
            labels:
              app: apache
          spec:
            containers:
              - name: apache
                image: "rhscl/httpd-24-rhel7"
                ports:
                  - containerPort: '{{ apache_port }}' 
                volumeMounts:
                  - name: html
                    mountPath: "/var/www/html/"
                    readOnly: true
                  - name: conf
                    mountPath: "/etc/httpd/httpd.conf"
                    readOnly: false # apache writes some stuff on /etc/httpd/conf
                  # https://access.redhat.com/solutions/4615501
                  # https://stackoverflow.com/a/44824976/3763807
                  # sed writes some temp file into /etc/httpd/conf.d/
            volumes:
              - name: html
                configMap:
                  name: '{{ ansible_operator_meta.name }}-apache-html' # name of the html configmap
              - name: conf
                configMap:
                  defaultMode: 420
                  name: '{{ ansible_operator_meta.name }}-apache-conf' # name of the conf configmap
                    
### config
- name: create html configmap
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache-html'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        index.html: '{{ index_html }}' # key will define file name

- name: create httpd.conf configmap
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache-conf'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        httpd.conf: '{{ rendered_template }}'
  vars:
    rendered_template: "{{ lookup('template', './httpd.conf.j2') }}"

### networking
- name: create service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          app: apache
      spec:
        selector:
          app: apache
        ports:
          - protocol: TCP
            port: 80
            targetPort: '{{ apache_port }}' 

- name: create route
  community.kubernetes.k8s:
    definition:
      kind: Route
      apiVersion: route.openshift.io/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        host: '{{ route_name }}-apache-operator-system.apps-crc.testing' # default: <route-name>[-<namespace>].<suffix> explicitly define so it can be changed later, this line could be ommited
        to:
          kind: Service
          name: '{{ ansible_operator_meta.name }}-apache'
        # route could be secured further...
        # tls:
        #   termination: edge            
        #   insecureEdgeTerminationPolicy: Allow | Redirect
        #   key: |-                      
        #     -----BEGIN PRIVATE KEY-----
        #     [...]
        #     -----END PRIVATE KEY-----
        #   certificate: |-              
        #     -----BEGIN CERTIFICATE-----
        #     [...]
        #     -----END CERTIFICATE-----
        #   caCertificate: |-            
        #     -----BEGIN CERTIFICATE-----
        #     [...]
        #     -----END CERTIFICATE-----

