---
- name: start apache
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: apache
        template:
          metadata:
            labels:
              app: apache
          spec:
            containers:
            - name: apache
              image: "rhscl/httpd-24-rhel7"
              ports:
                - containerPort: 11211 # to be parametrized
              volumeMounts:
               - name: html
                 mountPath: "/var/www/html/"
                 readOnly: true
            volumes:
                - name: html
                  configMap:
                    name: '{{ ansible_operator_meta.name }}-apache' # name of the configmap
 

- name: create service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        selector:
          app: apache
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80 # to be parametrized

- name: create configmap
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        index.html: |-
          <html>
              <body>
                  <h1>
                      Morty has some sick moves!
                  </h1>
              <img src="https://cdn.eldeforma.com/wp-content/uploads/2020/11/1509888664_5eY6d.gif" width=250/>
              </body>
          </html>

      

# kind: Route
# apiVersion: route.openshift.io/v1
# metadata:
#   name: toodea
#   namespace: apache-operator-system
#   uid: 663ad26f-b543-4001-830f-00bd1fc523b3
#   resourceVersion: '223636'
#   creationTimestamp: '2021-04-18T14:29:56Z'
#   annotations:
#     openshift.io/host.generated: 'true'
#   managedFields:
#     - manager: Mozilla
#       operation: Update
#       apiVersion: route.openshift.io/v1
#       time: '2021-04-18T14:29:56Z'
#       fieldsType: FieldsV1
#       fieldsV1:
#         'f:spec':
#           'f:port':
#             .: {}
#             'f:targetPort': {}
#           'f:to':
#             'f:kind': {}
#             'f:name': {}
#             'f:weight': {}
#           'f:wildcardPolicy': {}
#     - manager: openshift-router
#       operation: Update
#       apiVersion: route.openshift.io/v1
#       time: '2021-04-18T14:29:57Z'
#       fieldsType: FieldsV1
#       fieldsV1:
#         'f:status':
#           'f:ingress': {}
# spec:
#   host: toodea-apache-operator-system.apps-crc.testing
#   to:
#     kind: Service
#     name: sample-apache
#     weight: 100
#   port:
#     targetPort: 80
#   wildcardPolicy: None
# status:
#   ingress:
#     - host: toodea-apache-operator-system.apps-crc.testing
#       routerName: default
#       conditions:
#         - type: Admitted
#           status: 'True'
#           lastTransitionTime: '2021-04-18T14:29:57Z'
#       wildcardPolicy: None
#       routerCanonicalHostname: apps-crc.testing
