---
# tasks file for Apache
---
- name: start apache httpd
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-apache'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: apache
        template:
          metadata:
            labels:
              app: apache
          spec:
            containers:
            - name: apache
              # default entrypoint for now, default "It works" page served
              # command:
              # - httpd
              # - -m=64
              # - -o
              # - modern
              # - -v
              image: "docker.io/httpd:alpine"
              ports:
                - containerPort: 80