# permissions for end users to edit apaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apache-editor-role
rules:
- apiGroups:
  - web.quay.io
  resources:
  - apaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.quay.io
  resources:
  - apaches/status
  verbs:
  - get
