# permissions for end users to view apaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apache-viewer-role
rules:
- apiGroups:
  - web.example.com
  resources:
  - apaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.example.com
  resources:
  - apaches/status
  verbs:
  - get
