apiVersion: web.example.com/v1alpha1
kind: Apache
metadata:
  name: sample
  namespace: apache-operator-system # to be changed
spec:
  size: 3
  route_name: 'cloudwerkstatt'
  index_html: |-
    <html>
      <body>
        <h1>Morty has some sick moves!</h1>
        <img src="https://cdn.eldeforma.com/wp-content/uploads/2020/11/1509888664_5eY6d.gif" width=500/>
      </body>
    </html>
  apache_port: 8080
